//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanitex_Uzduotis
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int timetableId { get; set; }
        public int userId { get; set; }
        public int branchId { get; set; }
        public int time { get; set; }
    
        public virtual branch branch { get; set; }
        public virtual user user { get; set; }
    }
}
